// GENERATED by scripts/generate.mjs from features.json — do not edit.
// Regenerate with: pnpm --filter @navikt/browser-support-linting generate
/** The floor-derived levels this plugin asserts; guarded by the marker tests. */
export const levels = {
  "es": {
    "year": 2021,
    "caveats": [
      "Class static blocks (ES2022) need Safari 16.4; the floor is Safari 16. Bundlers lower them; unbundled code must not use them."
    ]
  },
  "baseline": {
    "year": 2022,
    "approximate": true
  }
};
