/**
 * Generates every derived artifact from features.json (the curated source of
 * truth) crossed with @mdn/browser-compat-data and the floor in
 * @navikt/browserslist-config/browsers.json:
 *
 *   data/support.json         per-feature per-family native minima, belowFloor
 *                             verdicts and blocking families (+ BCD version)
 *   lib/rules.generated.js    the wrapped-rule selection: es-x rule id, options,
 *                             floor-specific message suffix, docs url
 *   lib/configs.generated.js  rules maps for configs.recommended (the compat
 *                             rule pinned to the floor's browserslist query +
 *                             the wrapped rules) and configs.unbundled (es-x
 *                             restrict-to-es<year> minus the wrapped overlap)
 *   lib/levels.js             the asserted ES/Baseline levels (from features.json)
 *
 * The oxlint entrypoint (oxlint.js) is hand-written, not generated — it builds
 * its presets from lib/configs.generated.js at import time.
 *   README.md                 feature table between BEGIN/END generated-feature-table markers
 *
 * The selection rule: a feature is enforced by wrapped es-x rules iff its
 * disposition is "esx" AND it is unlowerable AND it is below the floor. All
 * availability is recomputed from BCD on every run — never trusted from a
 * snapshot — so a floor bump or a BCD update changes the generated files and
 * trips the CI drift gate (pnpm generate && git diff --exit-code).
 *
 * Hard failures (curation errors): unknown BCD key, unknown es-x rule, options
 * a rule's schema does not accept, a below-floor "compat" feature without a
 * compatCoverage verdict, a "safe" feature that is actually below floor.
 *
 * Generated files are checked in. Run:
 *   pnpm --filter @navikt/browser-support-linting generate
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const require = createRequire(import.meta.url);
const pkgDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const HEADER = `// GENERATED by scripts/generate.mjs from features.json — do not edit.\n// Regenerate with: pnpm --filter @navikt/browser-support-linting generate\n`;

/** caniuse family (browsers.json) -> BCD browser identifier. */
const BCD_FAMILIES = {
  chrome: 'chrome',
  edge: 'edge',
  firefox: 'firefox',
  safari: 'safari',
  ios_saf: 'safari_ios',
  opera: 'opera',
  samsung: 'samsunginternet_android',
};

const FAMILY_LABELS = {
  chrome: 'Chrome',
  edge: 'Edge',
  firefox: 'Firefox',
  safari: 'Safari',
  ios_saf: 'iOS Safari',
  opera: 'Opera',
  samsung: 'Samsung Internet',
};

const DISPOSITIONS = new Set(['esx', 'compat', 'syntax', 'safe']);
const PLUGIN_NS = 'browser-support';
const RESTRICT_CONFIG = 'flat/restrict-to-es2021';
const DOCS_BASE = 'https://github.com/navikt/browserslist-config/tree/main/packages/lint-plugin';

/** Walks a dotted BCD key to its __compat node, or throws. */
export function resolveBcdKey(bcd, key) {
  let node = bcd;
  for (const part of key.split('.')) {
    node = node?.[part];
    if (!node) throw new Error(`BCD key "${key}" does not exist — fix features.json`);
  }
  if (!node.__compat) throw new Error(`BCD key "${key}" has no __compat data — fix features.json`);
  return node.__compat;
}

/**
 * Reduces one browser's BCD support statements to { version, partial }.
 * version is a float (0 = "always"), or null when unsupported. Statements
 * behind flags, prefixes or alternative names do not count as support.
 * The earliest availability wins — a partial implementation counts (BCD
 * "partial" means a spec deviation in some detail, e.g. AbortSignal.timeout
 * aborting with the wrong error subclass, not absence) but is flagged when
 * it is what makes the feature reach further back than full support does.
 */
export function versionFromSupport(statements) {
  const list = (Array.isArray(statements) ? statements : [statements]).filter(
    (s) => s && !s.flags && !s.prefix && !s.alternative_name,
  );
  const parse = (s) => {
    const raw = s.version_added;
    if (raw === true) return 0;
    if (typeof raw !== 'string') return null;
    const num = Number.parseFloat(raw.replace(/^[≤~]/, ''));
    return Number.isFinite(num) ? num : null;
  };
  const minOf = (entries) =>
    entries.map(parse).filter((v) => v !== null).reduce((a, b) => Math.min(a, b), Infinity);
  const minFull = minOf(list.filter((s) => !s.partial_implementation));
  const minPartial = minOf(list.filter((s) => s.partial_implementation));
  const version = Math.min(minFull, minPartial);
  if (version === Infinity) return { version: null, partial: false };
  return { version, partial: minPartial < minFull };
}

/**
 * Native minimum per family for a whole feature (max over its BCD keys —
 * the feature is only "available" where every key is). null = unsupported.
 */
export function nativeSupport(bcd, keys) {
  const native = {};
  let partial = false;
  for (const family of Object.keys(BCD_FAMILIES)) native[family] = 0;
  for (const key of keys) {
    const compat = resolveBcdKey(bcd, key);
    for (const [family, bcdId] of Object.entries(BCD_FAMILIES)) {
      const { version, partial: isPartial } = versionFromSupport(compat.support[bcdId]);
      if (isPartial) partial = true;
      if (version === null) native[family] = null;
      else if (native[family] !== null) native[family] = Math.max(native[family], version);
    }
  }
  return { native, partial };
}

function formatBlocking(blocking, native, browsers) {
  return blocking.map((family) =>
    native[family] === null
      ? `${FAMILY_LABELS[family]} (not shipped)`
      : `${FAMILY_LABELS[family]} ${native[family]}+ (floor ${browsers[family]})`,
  );
}

function messageSuffix(blocking, native, browsers, guidance) {
  const parts = formatBlocking(blocking, native, browsers);
  const where =
    parts.length > 3
      ? "Not supported at Nav's browser floor."
      : `Below Nav's browser floor — needs ${parts.join(', ')}.`;
  return ` ${where} ${guidance ?? 'Polyfill or feature-guard it.'}`;
}

/**
 * Derives all generated content. Pure: inputs in, { support, warnings, files } out.
 * Throws on curation errors (see the header comment).
 */
export function derive({ levels, features }, browsers, bcd, esxPlugin, bcdVersion) {
  const families = Object.keys(browsers);
  for (const family of families) {
    if (!BCD_FAMILIES[family]) {
      throw new Error(`browsers.json family "${family}" has no BCD mapping — add it to BCD_FAMILIES in generate.mjs`);
    }
  }

  const warnings = [];
  const support = {};
  const wrappedRules = [];

  for (const [key, feature] of Object.entries(features)) {
    if (!DISPOSITIONS.has(feature.disposition)) {
      throw new Error(`Feature "${key}" has no valid disposition (got ${JSON.stringify(feature.disposition)})`);
    }
    if (!Array.isArray(feature.bcd) || feature.bcd.length === 0) {
      throw new Error(`Feature "${key}" lists no BCD keys`);
    }

    const { native, partial } = nativeSupport(bcd, feature.bcd);
    const blocking = families.filter(
      (family) => native[family] === null || native[family] > Number.parseFloat(browsers[family]),
    );
    const belowFloor = blocking.length > 0;

    support[key] = { disposition: feature.disposition, native, partial, belowFloor, blocking };

    switch (feature.disposition) {
      case 'esx': {
        if (!feature.unlowerable) {
          throw new Error(`Feature "${key}" has disposition "esx" but is not unlowerable — bundler-lowerable features belong to the config package ("syntax")`);
        }
        if (!Array.isArray(feature.esx) || feature.esx.length === 0) {
          throw new Error(`Feature "${key}" has disposition "esx" but lists no es-x rules`);
        }
        if (!belowFloor) {
          warnings.push(`"${key}" is no longer below the floor — move it to disposition "safe" and drop its rules`);
          break;
        }
        for (const { rule, aggressive } of feature.esx) {
          const baseRule = esxPlugin.rules[rule];
          if (!baseRule) {
            throw new Error(`Feature "${key}" maps to unknown es-x rule "${rule}" (installed eslint-plugin-es-x has no such rule)`);
          }
          const accepted = baseRule.meta.schema?.[0]?.properties ?? {};
          if (aggressive !== undefined && !('aggressive' in accepted)) {
            throw new Error(`Feature "${key}": rule "${rule}" does not accept an "aggressive" option`);
          }
          const options = {};
          if (aggressive !== undefined) options.aggressive = aggressive;
          if ('allowTestedProperty' in accepted) options.allowTestedProperty = true;
          wrappedRules.push({
            feature: key,
            esxId: rule,
            options: Object.keys(options).length > 0 ? options : null,
            messageSuffix: messageSuffix(blocking, native, browsers, feature.guidance),
            docsUrl: `${DOCS_BASE}#${key}`,
          });
        }
        break;
      }
      case 'compat': {
        if (belowFloor && !feature.compatCoverage) {
          throw new Error(`Feature "${key}" is below the floor but has no compatCoverage verdict — verify against eslint-plugin-compat and record it`);
        }
        if (!belowFloor && feature.compatCoverage) {
          warnings.push(`"${key}" is not below the floor — its compatCoverage field is unused`);
        }
        break;
      }
      case 'safe': {
        if (belowFloor) {
          throw new Error(`Feature "${key}" is asserted "safe" but is below the floor (blocking: ${blocking.join(', ')}) — reclassify it`);
        }
        break;
      }
      case 'syntax': {
        if (feature.unlowerable) {
          throw new Error(`Feature "${key}" has disposition "syntax" but is marked unlowerable — contradiction`);
        }
        break;
      }
    }
  }

  // configs.recommended rule map. The compat rule gets the floor's query as
  // its option (compat's schema takes one comma-joined browserslist string),
  // so the preset is self-contained — consumers need no browserslist config,
  // and forgetting one can no longer silently fall back to browserslist
  // defaults. Rule options also survive oxlint, unlike settings.
  const floorQuery = families.map((family) => `${family} >= ${browsers[family]}`).join(', ');
  const recommendedRules = { 'compat/compat': ['error', floorQuery] };
  for (const { esxId, options } of wrappedRules) {
    recommendedRules[`${PLUGIN_NS}/${esxId}`] = options ? ['error', options] : 'error';
  }

  // configs.unbundled: es-x restrict-to-es<asserted year>, minus rules already
  // wrapped in the recommended layer (they'd double-report).
  const restrict = esxPlugin.configs[RESTRICT_CONFIG];
  if (!restrict) {
    throw new Error(`Installed eslint-plugin-es-x has no "${RESTRICT_CONFIG}" config — the asserted es.year (${levels.es.year}) and the es-x version disagree`);
  }
  const wrappedIds = new Set(wrappedRules.map((r) => r.esxId));
  const unbundledRules = {};
  for (const ruleId of Object.keys(restrict.rules).sort()) {
    if (!wrappedIds.has(ruleId.replace(/^es-x\//, ''))) {
      unbundledRules[ruleId] = restrict.rules[ruleId];
    }
  }

  const supportJson = {
    description:
      'Generated availability verdicts: per-feature native browser minima from @mdn/browser-compat-data, compared against the floor in @navikt/browserslist-config/browsers.json. 0 means "always supported", null means "not shipped".',
    bcd: bcdVersion,
    floor: browsers,
    features: support,
  };

  const files = {
    'data/support.json': `${JSON.stringify(supportJson, null, 2)}\n`,
    'lib/rules.generated.js': [
      HEADER,
      '/** The wrapped-rule selection: below-floor unlowerable features × installed es-x rules. */\n',
      `export const wrappedRules = ${literal(wrappedRules)};\n`,
    ].join(''),
    'lib/configs.generated.js': [
      HEADER,
      `export const recommendedRules = ${literal(recommendedRules)};\n\n`,
      `export const unbundledRules = ${literal(unbundledRules)};\n`,
    ].join(''),
    'lib/levels.js': [
      HEADER,
      '/** The floor-derived levels this plugin asserts; guarded by the marker tests. */\n',
      `export const levels = ${literal(levels)};\n`,
    ].join(''),
  };

  return { support: supportJson, warnings, wrappedRules, recommendedRules, unbundledRules, files };
}

function literal(value) {
  return JSON.stringify(value, null, 2);
}

/** Renders the README feature table (wrapped features + below-floor Web APIs). */
export function featureTable({ features }, support, wrappedRules) {
  const rulesByFeature = new Map();
  for (const { feature, esxId } of wrappedRules) {
    if (!rulesByFeature.has(feature)) rulesByFeature.set(feature, []);
    rulesByFeature.get(feature).push(`\`${esxId}\``);
  }
  const rows = [];
  for (const [key, feature] of Object.entries(features)) {
    const verdict = support.features[key];
    if (!verdict.belowFloor) continue;
    if (feature.disposition !== 'esx' && feature.disposition !== 'compat') continue;
    const enforcement =
      feature.disposition === 'esx'
        ? rulesByFeature.get(key).join(', ')
        : feature.compatCoverage === 'caught'
          ? '`compat/compat`'
          : '⚠️ **not flagged today** — guard manually';
    const blocked = formatBlocking(verdict.blocking, verdict.native, support.floor).join(', ');
    rows.push(
      `| <a id="${key}"></a>**${feature.title}** | ${enforcement} | ${blocked} | ${feature.guidance ?? ''} |`,
    );
  }
  return [
    '| Feature | Enforced by | Blocked by | What to do |',
    '| --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

async function main() {
  const featuresJson = JSON.parse(readFileSync(path.join(pkgDir, 'features.json'), 'utf8'));
  const browsers = require('@navikt/browserslist-config/browsers.json');
  const bcd = require('@mdn/browser-compat-data');
  const { default: esxPlugin } = await import('eslint-plugin-es-x');

  const derived = derive(featuresJson, browsers, bcd, esxPlugin, bcd.__meta.version);
  for (const warning of derived.warnings) console.warn(`warning: ${warning}`);

  mkdirSync(path.join(pkgDir, 'data'), { recursive: true });
  for (const [name, content] of Object.entries(derived.files)) {
    writeFileSync(path.join(pkgDir, name), content);
    console.log(`wrote ${name}`);
  }

  // -- Update the README feature table between markers, if the README exists. --
  const readmePath = path.join(pkgDir, 'README.md');
  if (existsSync(readmePath)) {
    const table = featureTable(featuresJson, derived.support, derived.wrappedRules);
    const readme = readFileSync(readmePath, 'utf8');
    const begin = '<!-- BEGIN generated-feature-table -->';
    const end = '<!-- END generated-feature-table -->';
    if (readme.includes(begin) && readme.includes(end)) {
      const updated = readme.replace(
        new RegExp(`${begin}[\\s\\S]*?${end}`),
        `${begin}\n${table}\n${end}`,
      );
      writeFileSync(readmePath, updated);
      console.log('updated README.md feature table');
    } else {
      console.warn('README.md has no generated-feature-table markers — table not written');
    }
  }

  console.log(
    `generate: OK (${derived.wrappedRules.length} wrapped rules, ${Object.keys(derived.unbundledRules).length} unbundled rules, BCD ${derived.support.bcd})`,
  );
}

const isDirectRun = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isDirectRun) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
