/**
 * Generates every published artifact from browsers.json (the source of truth —
 * a flat map of caniuse family name -> pinned minimum version):
 *
 *   index.js        browserslist query array (ESM)
 *   index.cjs       the same array as CommonJS — the browserslist `extends`
 *                   protocol resolves configs with a synchronous require()
 *                   (both the JS library and browserslist-rs/Turbopack), and
 *                   those requires can run in runtimes we don't control
 *                   (editor extensions on Electron's bundled Node), so the
 *                   root keeps a real CJS twin
 *   esbuild.js      esbuild/Vite build.target strings (ESM)
 *   lightningcss.js Lightning CSS `targets` object (ESM; versions packed as major<<16|minor<<8|patch)
 *   remix.js        Remix 3 `remix/assets` `target` object (ESM; version strings, `ios` not `ios_saf`)
 *   README.md       support table between BEGIN/END generated-support-table markers
 *
 * Each ESM module also exports its value under the name 'module.exports', so a
 * stray require() of a subpath returns the raw value on Node >= 22.12.
 *
 * Generated files are checked in; CI fails if this script produces a diff.
 * Run: pnpm --filter @navikt/browserslist-config generate
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import browserslist from 'browserslist';
import { browserslistToTargets, transform as lightningcssTransform } from 'lightningcss';
import { transformSync as esbuildTransformSync } from 'esbuild';

const pkgDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const HEADER = `// GENERATED by scripts/generate.mjs from browsers.json — do not edit.\n// Regenerate with: pnpm --filter @navikt/browserslist-config generate\n`;

/** caniuse family -> esbuild engine name (families esbuild has no name for map to null). */
const ESBUILD_FAMILIES = {
  chrome: 'chrome',
  edge: 'edge',
  firefox: 'firefox',
  safari: 'safari',
  ios_saf: 'ios',
  opera: 'opera',
  // Samsung Internet is Chromium-based (v21 = Chromium 108); esbuild has no
  // "samsung" engine, so the chrome floor covers it.
  samsung: null,
};

/**
 * caniuse family -> Remix 3 `remix/assets` target key. Its target validator
 * rejects unknown keys, so every family needs an explicit mapping.
 */
const REMIX_FAMILIES = {
  chrome: 'chrome',
  edge: 'edge',
  firefox: 'firefox',
  safari: 'safari',
  ios_saf: 'ios',
  opera: 'opera',
  samsung: 'samsung',
};

const FAMILY_LABELS = {
  chrome: 'Chrome',
  edge: 'Edge',
  firefox: 'Firefox',
  safari: 'Safari (macOS)',
  ios_saf: 'Safari (iOS)',
  opera: 'Opera',
  samsung: 'Samsung Internet',
};

const FAMILY_NOTES = {
  ios_saf: 'Every iOS browser (Chrome, Firefox, Edge, …) uses WebKit',
  opera: '≈ Chromium 108',
  samsung: '≈ Chromium 108',
};

/** Derives all generated file contents from the parsed browsers.json map. Deterministic. */
export function derive(browsers) {
  const families = Object.keys(browsers);
  const queries = families.map((f) => `${f} >= ${browsers[f]}`);

  const esbuildTargets = families
    .map((f) => (ESBUILD_FAMILIES[f] === undefined ? unknownFamily(f) : ESBUILD_FAMILIES[f]))
    .map((engine, i) => (engine ? `${engine}${browsers[families[i]]}` : null))
    .filter(Boolean);
  const dedupedSorted = [...new Set(esbuildTargets)].sort();

  const lightningcssTargets = browserslistToTargets(browserslist(queries));

  const lightningcssLines = Object.entries(lightningcssTargets)
    .map(([family, packed]) => `export const ${identifier(family)} = ${packed};`)
    .join('\n');

  const remixTarget = Object.fromEntries(
    families
      .map((f) => [REMIX_FAMILIES[f] ?? unknownFamily(f, 'REMIX_FAMILIES'), browsers[f]])
      .sort(([a], [b]) => a.localeCompare(b)),
  );

  return {
    queries,
    esbuildTargets: dedupedSorted,
    lightningcssTargets,
    remixTarget,
    files: {
      'index.js': [
        HEADER,
        `const queries = ${literal(queries)};\n`,
        'export default queries;\n',
        REQUIRE_INTEROP('queries'),
      ].join(''),
      'index.cjs': [
        HEADER,
        "'use strict';\n",
        '// CJS twin of index.js for the browserslist `extends` require() path.\n',
        `module.exports = ${literal(queries)};\n`,
      ].join(''),
      'esbuild.js': [
        HEADER,
        `const targets = ${literal(dedupedSorted)};\n`,
        'export default targets;\n',
        REQUIRE_INTEROP('targets'),
      ].join(''),
      'lightningcss.js': [
        HEADER,
        '// Versions are packed as (major << 16) | (minor << 8) | patch.\n',
        `${lightningcssLines}\n`,
        `const targets = { ${Object.keys(lightningcssTargets).map(identifier).join(', ')} };\n`,
        'export default targets;\n',
        REQUIRE_INTEROP('targets'),
      ].join(''),
      'remix.js': [
        HEADER,
        '// Remix 3 asset server `target` (remix/assets createAssetServer).\n',
        `const target = ${literal(remixTarget)};\n`,
        'export default target;\n',
        REQUIRE_INTEROP('target'),
      ].join(''),
    },
  };
}

/** Lets a stray require() of the ESM module return the raw value (Node >= 22.12). */
const REQUIRE_INTEROP = (binding) => `export { ${binding} as 'module.exports' };\n`;

function identifier(key) {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)) {
    throw new Error(`"${key}" is not a valid identifier — cannot emit it as a named export`);
  }
  return key;
}

function unknownFamily(f, table = 'ESBUILD_FAMILIES') {
  throw new Error(`browsers.json family "${f}" has no mapping — add it to ${table} in generate.mjs`);
}

function literal(value) {
  const json = JSON.stringify(value, null, 2);
  // Guard: embedded double-quotes in string values would break key-unquoting below.
  if (/\\"/.test(json)) {
    throw new Error('browsers.json string values must not contain double-quotes');
  }
  // Unquote identifier keys so generated files read like handwritten JS.
  return json.replace(/"([A-Za-z_$][A-Za-z0-9_$]*)":/g, '$1:');
}

/** Lower bound of a caniuse version string ("108", "16.0-16.1", "all") as a float, or null. */
function lowerBound(version) {
  const first = version.split('-')[0];
  const num = Number.parseFloat(first);
  return Number.isFinite(num) ? num : null;
}

/**
 * Validates that the queries resolve (under the pinned caniuse-lite) to exactly the
 * configured families, with nothing below each floor.
 */
export function validateResolution(browsers, queries) {
  const resolved = browserslist(queries);
  const byFamily = new Map();
  for (const entry of resolved) {
    const [family, version] = entry.split(' ');
    if (!byFamily.has(family)) byFamily.set(family, []);
    byFamily.get(family).push(version);
  }

  const expectedFamilies = Object.keys(browsers).sort();
  const actualFamilies = [...byFamily.keys()].sort();
  if (JSON.stringify(expectedFamilies) !== JSON.stringify(actualFamilies)) {
    throw new Error(`Resolved families ${actualFamilies} != configured ${expectedFamilies}`);
  }

  const notes = [];
  for (const [family, versions] of byFamily) {
    const floor = Number.parseFloat(browsers[family]);
    const bounds = versions.map(lowerBound).filter((v) => v !== null);
    const min = Math.min(...bounds);
    if (min < floor) {
      throw new Error(`${family}: resolved version ${min} is below the ${floor} floor`);
    }
    if (min > floor) {
      notes.push(`${family}: floor is ${floor}, earliest caniuse-known version at/above it is ${min}`);
    }
  }
  return notes;
}

/** Renders the README support table rows. */
export function supportTable(browsers) {
  // caniuse-lite's unpacked agent data includes per-version release dates (epoch seconds).
  return import('caniuse-lite').then(({ agents }) => {
    const rows = Object.entries(browsers).map(([family, floor]) => {
      const agent = agents[family];
      const released = agent ? releaseDateFor(agent, floor) : null;
      const note = FAMILY_NOTES[family] ?? '';
      return `| ${FAMILY_LABELS[family] ?? family} | ${floor} | ${released ?? '—'} | ${note} |`;
    });
    return [
      '| Browser | Minimum version | Released | Notes |',
      '| --- | --- | --- | --- |',
      ...rows,
    ].join('\n');
  });
}

function releaseDateFor(agent, floor) {
  const dates = agent.release_date ?? {};
  const floorNum = Number.parseFloat(floor);
  // Exact key, "N.0" key, or the earliest version key whose lower bound is >= floor.
  const candidates = Object.keys(dates)
    .map((key) => ({ key, bound: lowerBound(key) }))
    .filter((c) => c.bound !== null && c.bound >= floorNum)
    .sort((a, b) => a.bound - b.bound);
  const match = dates[floor] ?? dates[`${floor}.0`] ?? (candidates[0] ? dates[candidates[0].key] : null);
  if (!match) return null;
  return new Date(match * 1000).toISOString().slice(0, 7);
}

async function main() {
  const browsers = JSON.parse(readFileSync(path.join(pkgDir, 'browsers.json'), 'utf8'));
  const derived = derive(browsers);

  // -- Validate before writing anything. --
  const notes = validateResolution(browsers, derived.queries);
  for (const note of notes) console.warn(`note: ${note}`);

  for (const value of [derived.queries, derived.esbuildTargets, derived.lightningcssTargets, derived.remixTarget]) {
    const roundTripped = JSON.parse(JSON.stringify(value));
    if (JSON.stringify(roundTripped) !== JSON.stringify(value)) {
      throw new Error('An export is not JSON-serializable — browserslist-rs consumers would break');
    }
  }

  esbuildTransformSync('class A { static { A.ready = true } }', { target: derived.esbuildTargets });
  lightningcssTransform({
    filename: 'smoke.css',
    code: Buffer.from(':root { color: oklch(0.5 0.1 200); }'),
    targets: derived.lightningcssTargets,
  });

  // -- Write generated modules. --
  for (const [name, content] of Object.entries(derived.files)) {
    writeFileSync(path.join(pkgDir, name), content);
    console.log(`wrote ${name}`);
  }

  // -- Update the README support table between markers, if the README exists. --
  const readmePath = path.join(pkgDir, 'README.md');
  if (existsSync(readmePath)) {
    const table = await supportTable(browsers);
    const readme = readFileSync(readmePath, 'utf8');
    const begin = '<!-- BEGIN generated-support-table -->';
    const end = '<!-- END generated-support-table -->';
    if (readme.includes(begin) && readme.includes(end)) {
      const updated = readme.replace(
        new RegExp(`${begin}[\\s\\S]*?${end}`),
        `${begin}\n${table}\n${end}`,
      );
      writeFileSync(readmePath, updated);
      console.log('updated README.md support table');
    } else {
      console.warn('README.md has no generated-support-table markers — table not written');
    }
  }

  console.log('generate: OK');
}

const isDirectRun = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isDirectRun) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
