// GENERATED by scripts/generate.mjs from browsers.json — do not edit.
// Regenerate with: pnpm --filter @navikt/browserslist-config generate
const targets = [
  "chrome108",
  "edge108",
  "firefox121",
  "ios16",
  "opera94",
  "safari16"
];
export default targets;
export { targets as 'module.exports' };
