// GENERATED by scripts/generate.mjs from browsers.json — do not edit.
// Regenerate with: pnpm --filter @navikt/browserslist-config generate
const queries = [
  "chrome >= 108",
  "edge >= 108",
  "firefox >= 121",
  "safari >= 16",
  "ios_saf >= 16",
  "opera >= 94",
  "samsung >= 21"
];
export default queries;
export { queries as 'module.exports' };
