// GENERATED by scripts/generate.mjs from browsers.json — do not edit.
// Regenerate with: pnpm --filter @navikt/browserslist-config generate
'use strict';
// CJS twin of index.js for the browserslist `extends` require() path.
module.exports = [
  "chrome >= 108",
  "edge >= 108",
  "firefox >= 121",
  "safari >= 16",
  "ios_saf >= 16",
  "opera >= 94",
  "samsung >= 21"
];
