// GENERATED by scripts/generate.mjs from browsers.json — do not edit.
// Regenerate with: pnpm --filter @navikt/browserslist-config generate
// Versions are packed as (major << 16) | (minor << 8) | patch.
export const chrome = 7077888;
export const edge = 7077888;
export const firefox = 7929856;
export const ios_saf = 1048576;
export const opera = 6160384;
export const safari = 1048576;
export const samsung = 1376256;
const targets = { chrome, edge, firefox, ios_saf, opera, safari, samsung };
export default targets;
export { targets as 'module.exports' };
