// GENERATED by scripts/generate.mjs from browsers.json — do not edit.
// Regenerate with: pnpm --filter @navikt/browserslist-config generate
// Remix 3 asset server `target` (remix/assets createAssetServer).
const target = {
  chrome: "108",
  edge: "108",
  firefox: "121",
  ios: "16",
  opera: "94",
  safari: "16",
  samsung: "21"
};
export default target;
export { target as 'module.exports' };
